//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
//addSbtPlugin("io.spray"                  % "sbt-revolver"      % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.0.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.7")
//addSbtPlugin("ch.epfl.scala"             % "sbt-release-early" % "2.1.1")
